### ISSUE TITLE
App crashes when granting permission 

### ISSUE THREAD

**Issue by isreal6ix** [ATryder/TEdit#6]
***Actual Behavior***

Turns out that when user clicks on the allow button, it crashes 

***How to produce the bug***

 * when it brings up a window, seeking for users permission on media files, click on the allow button 
 * it'll crash 

***TEST TOOLS***

* Operating system : Android 6.0
* Phone : Infinix hot s
* TEdit v2.1.1

***Recording of the bug is show below......***

Watch the video below to see how it behaves.... 

https://youtu.be/dWXEBdjNwfs

**Comment by ATryder** [comment]
Any chance you could supply LogCat output? I don't have a 6.0 device to test, just 8.0 and it's not a problem on that device.

**Comment by ATryder** [comment]
Fixed as of https://github.com/ATryder/TEdit/commit/9d2774896df585ce42b76f5f19aa4b1e9e576738

**Comment by lmagyar** [comment]
Still crashes on Android 8, Galaxy A3... Permission granted, after selecting external storage to open anything, it crashes. Opening a file through browser is impossible, file is Untitled and can't be than saved on SD card.
